INFO: Starting training:
        Epochs:          200
        Batch size:      32
        Learning rate:   0.001
        Training size:   2533
        Validation size: 281
        Checkpoints:     True
        Device:          cuda
        Images scaling:  0.5
        Mixed Precision: True
Epoch 1/200:   0%|                                                                                                                                                                | 0/2533 [00:00<?, ?img/s]/home/drswchorndlaptop/anaconda3/envs/yolov5_py3/lib/python3.8/site-packages/torch/nn/functional.py:718: UserWarning: Named tensors and all their associated APIs are an experimental feature and subject to change. Please do not use them for anything important until they are released as stable. (Triggered internally at  /opt/conda/conda-bld/pytorch_1623448234945/work/c10/core/TensorImpl.h:1156.)
  return torch.max_pool2d(input, kernel_size, stride, padding, dilation, ceil_mode)
Epoch 1/200:   0%|                                                                                                                                                                | 0/2533 [00:01<?, ?img/s]
Traceback (most recent call last):
  File "train.py", line 179, in <module>
    train_net(net=net,
  File "train.py", line 89, in train_net
    masks_pred = net(images)
  File "/home/drswchorndlaptop/anaconda3/envs/yolov5_py3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/drswchorndlaptop/Pytorch-UNet/unet/unet_model.py", line 34, in forward
    x = self.up4(x, x1)
  File "/home/drswchorndlaptop/anaconda3/envs/yolov5_py3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/drswchorndlaptop/Pytorch-UNet/unet/unet_parts.py", line 68, in forward
    return self.conv(x)
  File "/home/drswchorndlaptop/anaconda3/envs/yolov5_py3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/drswchorndlaptop/Pytorch-UNet/unet/unet_parts.py", line 25, in forward
    return self.double_conv(x)
  File "/home/drswchorndlaptop/anaconda3/envs/yolov5_py3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/drswchorndlaptop/anaconda3/envs/yolov5_py3/lib/python3.8/site-packages/torch/nn/modules/container.py", line 139, in forward
    input = module(input)
  File "/home/drswchorndlaptop/anaconda3/envs/yolov5_py3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/drswchorndlaptop/anaconda3/envs/yolov5_py3/lib/python3.8/site-packages/torch/nn/modules/conv.py", line 443, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "/home/drswchorndlaptop/anaconda3/envs/yolov5_py3/lib/python3.8/site-packages/torch/nn/modules/conv.py", line 439, in _conv_forward
    return F.conv2d(input, weight, bias, self.stride,
RuntimeError: CUDA out of memory. Tried to allocate 300.00 MiB (GPU 0; 7.80 GiB total capacity; 5.83 GiB already allocated; 240.44 MiB free; 6.11 GiB reserved in total by PyTorch)